"""empty message

Revision ID: 26f35fb90e5f
Revises: 
Create Date: 2017-10-26 08:48:36.933685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f35fb90e5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('kw_id', sa.String(), nullable=False),
    sa.Column('kw_name', sa.String(), nullable=True),
    sa.Column('last_change', sa.Date(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('kw_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keywords')
    # ### end Alembic commands ###
